<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-DTAJN93" failures="4" tests="12" name=" Spentra " time="484.658" errors="0" timestamp="25 Jan 2021 03:41:18 GMT">
  <testcase classname="com.functional.tests.Login" name="negativeLoginTest" time="28.109"/>
  <testcase classname="com.functional.tests.Login" name="negativeLoginTest" time="11.791"/>
  <testcase classname="com.functional.tests.Login" name="negativeLoginTest" time="25.381"/>
  <testcase classname="com.functional.tests.Login" name="negativeLoginTest" time="16.551"/>
  <testcase classname="com.functional.tests.Login" name="logintoApplication" time="18.12"/>
  <testcase classname="com.functional.tests.AddEmp" name="navigateToAddEmployee" time="19.781"/>
  <testcase classname="com.functional.tests.AddEmp" name="addEmployeeDetails" time="55.284">
    <failure type="java.lang.AssertionError" message="expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]
	at com.pages.AddEmpPage.verifyMessage(AddEmpPage.java:170)
	at com.functional.tests.AddEmp.addEmployeeDetails(AddEmp.java:34)
	at com.framework.Setup.executeTest(Setup.java:39)
	at com.framework.Start.main(Start.java:23)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeDetails -->
  <testcase classname="com.functional.tests.AddEmp" name="addEmployeeDetails" time="30.547">
    <failure type="java.lang.AssertionError" message="expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]
	at com.pages.AddEmpPage.verifyMessage(AddEmpPage.java:170)
	at com.functional.tests.AddEmp.addEmployeeDetails(AddEmp.java:34)
	at com.framework.Setup.executeTest(Setup.java:39)
	at com.framework.Start.main(Start.java:23)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeDetails -->
  <testcase classname="com.functional.tests.AddEmp" name="addEmployeeDetails" time="63.773">
    <failure type="java.lang.AssertionError" message="expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]
	at com.pages.AddEmpPage.verifyMessage(AddEmpPage.java:170)
	at com.functional.tests.AddEmp.addEmployeeDetails(AddEmp.java:34)
	at com.framework.Setup.executeTest(Setup.java:39)
	at com.framework.Start.main(Start.java:23)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeDetails -->
  <testcase classname="com.functional.tests.AddEmp" name="addEmployeeDetails" time="53.73">
    <failure type="java.lang.AssertionError" message="expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Employee profile with this Employee ID already exists.] but found [Employee added successfully.]
	at com.pages.AddEmpPage.verifyMessage(AddEmpPage.java:170)
	at com.functional.tests.AddEmp.addEmployeeDetails(AddEmp.java:34)
	at com.framework.Setup.executeTest(Setup.java:39)
	at com.framework.Start.main(Start.java:23)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeDetails -->
  <testcase classname="com.functional.tests.AddEmp" name="verifyEmployeeDetails" time="142.091"/>
  <testcase classname="com.functional.tests.AddEmp" name="logoutFromApplication" time="16.602"/>
</testsuite> <!--  Spentra  -->
